apiVersion: v1
kind: Service
metadata:
  name: target-app-service
  namespace: autoscaler
  labels:
    app: target-app
spec:
  type: NodePort
  selector:
    app: target-app
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30007
